import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import BootstrapBundle from "@/hooks/BootstrapBundle";
import Hero from "@/components/Hero";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Post App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Hero />
        <div className="container">
          <BootstrapBundle />
        {children}
        </div>
        <Footer />
        </body>
    </html>
  );
}
